apiVersion: v1
kind: Secret
metadata:
  name: demo-db
  namespace: webapps
type: Opaque
stringData:
  type: postgresql
  host: demo-db
  port: "5432"
  username: "user"
  password: "pass"
  database: "petclinic"
  uri: "postgresql://user:pass@demo-db:5432/petclinic"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-db
  namespace: webapps
spec:
  ports:
    - port: 5432
  selector:
    app: demo-db
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-db
  namespace: webapps
  labels:
    app: demo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
        - name: postgresql
          image: postgres:15.4
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: database
          ports:
            - containerPort: 5432
              name: postgresql
          livenessProbe:
            tcpSocket:
              port: postgresql
          readinessProbe:
            tcpSocket:
              port: postgresql
          startupProbe:
            tcpSocket:
              port: postgresql
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
